name: CI

on:
  push:
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  build-lib:
    strategy:
      matrix:
        os: [ ubuntu-22.04, macos-14, windows-2022 ]
        jvm-version: [ 21 ]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
      - name: Set up JDK ${{ matrix.jvm-version }}
        uses: actions/setup-java@1bcf9fb12cf4aa7d266a90ae39939e61372fe520 # v5
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.jvm-version }}
      - name: Setup sbt launcher
        uses: sbt/setup-sbt@3afe9cf056c5d139bfc46579af1192d77a2f0821 # v1
      - name: Build and test
        run: sbt +test
