name: CI

on:
  push:
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  build-lib:
    strategy:
      matrix:
        os: [ ubuntu-22.04, macos-14, windows-2022 ]
        jvm-version: [ 21 ]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - name: Set up JDK ${{ matrix.jvm-version }}
        uses: actions/setup-java@03ad4de0992f5dab5e18fcb136590ce7c4a0ac95 # v5
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.jvm-version }}
      - name: Setup sbt launcher
        uses: sbt/setup-sbt@bfea3c5f48abd221b04a6df4798aa5eb8b6a2baf # v1
      - name: Build and test
        run: sbt +test
